-- Create a table to store dynamic customer data
create table customers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  data jsonb not null
);

-- Enable Row Level Security (RLS)
alter table customers enable row level security;

-- Allow full public access (for demo purposes)
-- In a real production app, you might want to restrict this
create policy "Enable all for all" on customers
for all using (true) with check (true);
